<?php
$form->prepare();
$this->headLink()->appendStylesheet($this->assetUrl('css/hierarchy.css', 'Hierarchy'));
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'sites resources');

$rowTemplate = '
<div class="resource-row row">
    <span class="sortable-handle"></span>
    <span class="data-value" data-row-key="child-search"></span>
    <ul class="actions"><li>
' . $this->hyperlink('', '#', ['class' => 'o-icon-delete', 'title' => $this->translate('Remove hierarchy')])
  . '<input type="hidden" class="resource-id" name="site_hierarchies[]">
    </li></ul>
</div>';
?>


<?php echo $this->pageTitle($this->translate('Site Hierarchies'), 1, $this->translate('Sites')); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<div id="site-hierarchies" class="selector-rows <?php echo ((count($siteHierarchies) > 0)) ? '' : 'empty'; ?>"
    data-existing-rows="<?php echo $this->escapeHtml(json_encode($siteHierarchies)); ?>"
    data-row-template="<?php echo $this->escapeHtml($rowTemplate); ?>">
    <div class="resource-rows"></div>
    <div class="no-resources"><?php echo $this->translate('No hierarchies are assigned to this site.'); ?></div>
</div>

<div id="hierarchy-selector" class='hierarchy-selector selector sidebar active'>
    <a href="#" class="mobile-only sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close'); ?></span></a>
    <div class="resources-available" data-all-resources-count="<?php echo count($allHierarchies); ?>">
        <h3><?php echo $this->translate('Click on a hierarchy to add it to the edit panel.'); ?></h3>
        <input type="text" class="selector-filter" placeholder=" <?php echo $this->escapeHtml($this->translate('Filter hierarchies')); ?>">
        <ul>
            <li class="total-count-heading"><?php echo $this->translate('Hierarchies'); ?> (<span class="selector-total-count"><?php echo count($allHierarchies); ?></span>)
                <ul class="selectable-list">
                    <li class='selector-parent show'>
                        <ul>
                            <?php foreach ($allHierarchies as $key => $value): ?>
                            <?php $value = $value ?: '[Untitled]'; ?>
                            <li class='selector-child'
                                data-child-search="<?php echo $this->escapeHtml($value); ?>"
                                data-resource-id="<?php echo $this->escapeHtml($key); ?>">
                                <div class="description"></div>
                                <span><?php echo $this->escapeHtml($value); ?></span>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="resources-unavailable">
        <p><?php echo sprintf('All %s have been added.', 'hierarchies'); ?></p>
    </div>
</div>

<?php echo $this->form()->closeTag($form); ?>

<script>
(function($) {
    $(document).ready(function() {
        new Sortable(document.querySelector('#site-hierarchies .resource-rows'), {
            draggable: '.resource-row',
            handle: '.sortable-handle',
        });

        Omeka.initializeSelector('#site-hierarchies', '#hierarchy-selector');
    });
})(jQuery)
</script>

<style>
.selector .selectable-list .selector-parent:after {
    content:none;
}
.selector .selectable-list .selector-parent.show:after {
    content:none;
}
</style>
