<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$label = isset($data['label']) && '' !== trim($data['label']) ? $data['label'] : null;
$itemSet = isset($data['itemSet']) && '' !== trim($data['itemSet']) ? $data['itemSet'] : null;

$itemSetElement = (new Laminas\Form\Element\Select('itemSet'))
    ->setLabel($this->translate('Item Set'))
    ->setValueOptions($itemSetArray)
    ->setEmptyOption($this->translate('Select Item Set...'))
    ->setValue($itemSet ?? '')
    ->setAttribute('data-name', 'itemSet')
?>
<label><?php echo $translate('Label'); ?><input type="text" data-name="label" value="<?php echo $escape($label); ?>"></label>
<label><?php echo $translate('Item Set'); ?><?php echo $this->formElement($itemSetElement); ?></label>
