<?php
$translate = $this->plugin('translate');
if ($resource->getControllerName() == 'item-set') {
    $groupings = $this->api()->search('item_hierarchy_grouping', ['item_set' => $resource->id(), 'sort_by' => 'position'])->getContent();
    $iterate = function ($groupings, $resource) use (&$iterate, &$allGroupings, &$currentHierarchy) {
        foreach ($groupings as $key => $grouping) {
            // Continue if all relevant groupings in hierarchy have been printed
            if (isset($allGroupings) && count($allGroupings) == 0) {
                continue;
            }

            if ($currentHierarchy != $grouping->getHierarchy() || $grouping->getParentGrouping() == 0) {
                if (!is_null($currentHierarchy)) {
                    echo '</span></dd>';
                }
                echo '<dd class="value">';
                echo '<span class="value-content">';
                $currentHierarchy = $grouping->getHierarchy();
                $allGroupings = $this->api()->search('item_hierarchy_grouping', ['hierarchy' => $currentHierarchy])->getContent();
            }

            if ($grouping->getParentGrouping() != 0) {
                // $iterate through any groupings with current grouping as child
                $parentArray = array_filter($allGroupings, function($parent) use($grouping) {
                    return $parent->id() == $grouping->getParentGrouping();
                });
                if (count($parentArray) > 0) {
                    $iterate($parentArray, $resource);
                    break;
                }
            }

            try {
                $itemSet = $this->api()->read('item_sets', $grouping->getItemSet())->getContent();
            } catch (\Exception $e) {
                // Print groupings without assigned itemSet
                $itemSet = null;
                echo $grouping->getLabel();
            }
            
            if (!is_null($itemSet)) {
                // Bold groupings with current itemSet assigned
                if ($grouping->getItemSet()->getId() == $resource->id()) {
                    echo "<b>" . $itemSet->link($grouping->getLabel()) . "</b>";
                } else {
                    echo $itemSet->link($grouping->getLabel());
                }
            }

            // Return any groupings with current grouping as parent
            $childArray = array_filter($allGroupings, function($child) use($grouping) {
                return $child->getParentGrouping() == $grouping->id();
            });

            // Remove already printed groupings from $allGroupings array
            $allGroupings = array_filter($allGroupings, function($child) use($grouping) {
                return $child->id() != $grouping->id();
            });
            
            if (count($childArray) > 0) {
                echo " <span class=\"hierarchy-divider fas fa-caret-right\"></span> ";
                $iterate($childArray, $resource);
            }
        }
    };

    if ($groupings) {
        echo '<dl><div class="property">';
        echo '<dt>' . $translate('Hierarchies') . '</dt>';
        $iterate($groupings, $resource);
        echo '</span></dd></dl>';
    }
}
$options = [];
if ($this->siteSetting('exclude_resources_not_in_site')) {
    $options['siteId'] = $this->currentSite()->id();
}
echo $resource->displayValues($options);
?>
