<?php
$itemSets = [];
switch (get_class($resource)) {
    case 'Omeka\Api\Representation\ItemRepresentation':
        $itemSets = $resource->itemSets();
        $item = $resource;
        break;
    case 'Omeka\Api\Representation\ItemSetRepresentation':
        $itemSets[] = $resource;
        $item = null;
        break;
    default:
        return;
}

if (!$itemSets) {
    return;
}

// Get order for printing hierarchies by comparing resource/resource's itemSets to position on Hierarchy page
$itemSetOrder = array_filter($api->search('hierarchy_grouping', ['sort_by' => 'position'], ['returnScalar' => 'item_set'])->getContent());
$itemSets = !empty($item) ? array_replace(array_flip($itemSetOrder), $item->itemSets()) : $itemSets;

$siteHierarchiesArray = $this->siteSetting('site_hierarchies');
$siteGroupings = array();
$groupings = array();
foreach ($itemSets as $itemSet) {
    if (is_numeric($itemSet)) {
        continue;
    }
    $groupings = $api->search('hierarchy_grouping', ['item_set' => $itemSet->id(), 'sort_by' => 'position'])->getContent();
    // Only show groupings/hierarchies assigned by Hierarchy option in site's context menu
    foreach ($groupings as $grouping) {
        foreach ($siteHierarchiesArray as $siteHierarchy) {
            if ($grouping->getHierarchy()->getId() == $siteHierarchy['id']) {
                $siteGroupings[][] = $grouping;
            }
        }
    }
}

// Return if no groupings/hierarchies found
if (!$siteGroupings) {
    return;
}
?>

<dl class="hierarchies">
    <div class="property">
        <dt><?php echo $this->translate('Hierarchies'); ?></dt>
        <dd class="value">
            <?php foreach ($siteGroupings as $groupings): ?>
            <?php echo $this->hierarchyHelper()->buildNestedList($groupings, $itemSet, $item, true); ?>
            <?php endforeach; ?>
        </dd>
    </div>
</dl>
