<div>
    <?php
    // Show label if hierarchy_show_label checked in config
     if ($this->setting('hierarchy_show_label')) {
         echo '<h4>' . $hierarchy->getLabel() . '</h4>';
     }
    ?>
    <ul>
        <?php $iterate = function ($groupings) use (&$iterate, $allGroupings) {
            foreach ($groupings as $grouping) {
                $groupingName = $grouping['data']['label'] ?: ' ';
                $groupingSet = $grouping['data']['itemSet'];
                $groupingID = $grouping['data']['groupingID'];
                if (empty($groupingSet)) {
                    echo '<li>' . $this->hyperlink($groupingName, $this->url('site/hierarchy', ['site-slug' => $this->currentSite()->slug(), 'grouping-id' => $groupingID])) . '</li>';
                } else {
                    try {
                        $itemSet = $this->api()->read('item_sets', $groupingSet)->getContent();
                        // Show itemSet count if hierarchy_show_count checked in config
                        $groupingObject = $this->api()->read('hierarchy_grouping', $groupingID)->getContent();
                        $itemSetCount = $this->setting('hierarchy_show_count') ? $this->hierarchyHelper()->itemSetCount($groupingObject, $allGroupings) : '';
                        // If no grouping label, show itemSet title as grouping heading
                        $groupingName = $grouping['data']['label'] ?: $itemSet->title();
                        echo '<li>' . $this->hyperlink($groupingName, $this->url('site/hierarchy', ['site-slug' => $this->currentSite()->slug(), 'grouping-id' => $groupingID])) . $itemSetCount;
                    } catch (NotFoundException $e) {
                        echo '<li>' . $this->hyperlink($groupingName, $this->url('site/hierarchy', ['site-slug' => $this->currentSite()->slug(), 'grouping-id' => $groupingID])) . '</li>';
                    }
                }
                if (isset($grouping['children'])) {
                    echo '<ul>';
                    $iterate($grouping['children']);
                    echo '</ul>';
                }
            }
        };
        $iterate($hierarchyData); ?>
    </ul>
</div>
